### ISSUE TITLE
RitualSmartAttack.js-question

### ISSUE THREAD

**Issue by 2cbskoupas** [Sau1707/Grepolis#4]
Hello, how could i modify it to cancel the attacks after some time? I tried to use the .click method to the element with class="button_new square remove js-delete cancelable" (it is the cancel button from the dropdown list).  I also tried the other cancel button on the command overview tab but didnt work. Sorry if my question is very noob but i just started learning :)

**Comment by Sau1707** [comment]
I know what are you trying to do...this is just annoying for the player, and you might get banned for nothing, are you really sure you wanna do that?

**Comment by 2cbskoupas** [comment]
For educational purposes only!

**Comment by Sau1707** [comment]
In any case they added a settings that the player don't receive the notification, so it's useless now

**Comment by 2cbskoupas** [comment]
I know i just want it for fun to mess around hehe

**Comment by gredfc** [comment]
I have a question to do ,this script to modify it ,  divert city troops when enemy attack comes?is there a way to do this?
thenks.
